// POS visual language, ported verbatim from pos.html's inline style map.
// Inline styles (not CSS classes) are deliberate: pixel parity with the live
// tool during the trial, and zero risk of cross-module class collisions.
import type { CSSProperties } from 'react'

export const SEA = '#2c92bf'
export const SEA_DEEP = '#1f6f93'
export const SUN = '#e8833a'
export const CLAY = '#c2553f' // terracotta — discounts, voids, alerts
export const SAND = '#faf6ee'
export const CARD = '#ffffff'
export const INK = '#2c2620'
export const MUTE = '#9a9183'
export const LINE = '#ece3d2'

const styles = {
  app: { direction: 'rtl', fontFamily: '-apple-system,BlinkMacSystemFont,sans-serif', background: SAND, color: INK, height: '100dvh', display: 'flex', flexDirection: 'column', overflow: 'hidden', WebkitUserSelect: 'none', userSelect: 'none' },
  scroll: { flex: 1, overflowY: 'auto', padding: '12px 12px 0', WebkitOverflowScrolling: 'touch' },
  guestRow: { display: 'flex', gap: 8, marginBottom: 16 },
  stepper: { flex: 1, minWidth: 0, background: CARD, border: '1px solid ' + LINE, borderRadius: 16, padding: '10px 8px 12px', textAlign: 'center' },
  stepLbl: { fontSize: 12, fontWeight: 600, color: MUTE, display: 'block', marginBottom: 8 },
  stepCtl: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 4 },
  stepBtn: { width: 38, height: 38, flexShrink: 0, borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, color: SEA_DEEP, fontSize: 24, fontWeight: 700, lineHeight: 1, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 0 },
  stepNum: { fontSize: 24, fontWeight: 800, flex: 1, lineHeight: 1 },
  headTotal: { flex: 1, background: SEA, borderRadius: 16, padding: '10px 8px', color: '#fff', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', position: 'relative' },
  headTotalNum: { fontSize: 34, fontWeight: 900, lineHeight: 1 },
  headTotalLbl: { fontSize: 12, opacity: 0.9, marginTop: 2 },
  familyTag: { fontSize: 10, fontWeight: 700, background: SUN, color: '#fff', padding: '2px 7px', borderRadius: 8, position: 'absolute', top: 6, insetInlineStart: 6 },
  section: { marginBottom: 16 },
  catHead: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8, paddingInlineStart: 2 },
  catDot: { width: 9, height: 9, borderRadius: '50%', flexShrink: 0 },
  catTitle: { fontSize: 15, fontWeight: 800, margin: 0, letterSpacing: '-0.2px' },
  catTag: { fontSize: 10, fontWeight: 700, color: MUTE, marginInlineStart: 'auto', letterSpacing: '0.2px' },
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  card: { background: CARD, border: '1.5px solid', borderRadius: 16, padding: 11, transition: 'border-color .15s,box-shadow .15s' },
  cardTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 10, gap: 6 },
  cardNameWrap: { display: 'flex', alignItems: 'center', gap: 6, minWidth: 0, flexWrap: 'wrap' },
  cardName: { fontSize: 14, fontWeight: 700, lineHeight: 1.25 },
  cardPrice: { fontSize: 15, fontWeight: 800, flexShrink: 0 },
  cardCtl: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 6 },
  qBtn: { width: 46, height: 46, borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, color: INK, fontSize: 28, fontWeight: 700, lineHeight: 1, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 0 },
  qNum: { fontSize: 24, fontWeight: 900, minWidth: 24, textAlign: 'center', lineHeight: 1 },
  delBtn: { width: 26, height: 26, borderRadius: 8, border: 'none', background: '#f6eee2', color: MUTE, fontSize: 13, fontWeight: 700, cursor: 'pointer', flexShrink: 0, lineHeight: 1, padding: 0 },
  addOpen: { width: '100%', padding: 14, borderRadius: 16, border: '1.5px dashed #d9ccb2', background: 'transparent', color: MUTE, fontSize: 14, fontWeight: 700, cursor: 'pointer', marginTop: 4 },
  addForm: { background: CARD, border: '1.5px solid ' + SUN, borderRadius: 16, padding: 12, marginTop: 4, display: 'flex', flexDirection: 'column', gap: 8 },
  addInput: { width: '100%', padding: '12px 14px', borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, fontSize: 15, fontWeight: 600, color: INK, outline: 'none', textAlign: 'right' },
  addRow: { display: 'flex', gap: 8 },
  ohPick: { padding: '0 16px', borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, color: MUTE, fontSize: 13, fontWeight: 700, cursor: 'pointer', whiteSpace: 'nowrap' },
  ohPickOn: { background: SEA, color: '#fff', borderColor: 'transparent' },
  addBtns: { display: 'flex', gap: 8 },
  addCancel: { flex: 1, padding: 12, borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, color: INK, fontSize: 14, fontWeight: 700, cursor: 'pointer' },
  addConfirm: { flex: 1, padding: 12, borderRadius: 12, border: 'none', background: SUN, color: '#fff', fontSize: 14, fontWeight: 700, cursor: 'pointer' },
  dock: { background: CARD, borderTop: '1px solid ' + LINE, boxShadow: '0 -6px 24px rgba(44,38,32,.10)', padding: '9px 12px calc(9px + env(safe-area-inset-bottom))', flexShrink: 0 },
  modeRow: { display: 'flex', gap: 6, background: SAND, borderRadius: 12, padding: 4, marginBottom: 8 },
  modeBtn: { flex: 1, padding: '8px 0', borderRadius: 8, border: 'none', background: 'transparent', color: MUTE, fontSize: 13, fontWeight: 700, cursor: 'pointer', transition: 'all .15s' },
  modeOn: { background: SEA, color: '#fff', boxShadow: '0 2px 8px rgba(44,146,191,.2)' },
  modeOnSun: { background: SUN, color: '#fff', boxShadow: '0 2px 8px rgba(232,131,58,.2)' },
  billRow: { display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12, marginBottom: 8 },
  breakdown: { flex: 1, display: 'flex', flexDirection: 'column', gap: 4, minWidth: 0 },
  line: { display: 'flex', justifyContent: 'space-between', gap: 8 },
  lineLbl: { fontSize: 12, color: MUTE, fontWeight: 600, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  lineVal: { fontSize: 13, fontWeight: 700, color: INK, flexShrink: 0 },
  grand: { textAlign: 'end', flexShrink: 0 },
  grandLbl: { fontSize: 12, color: MUTE, fontWeight: 600, display: 'block', marginBottom: -2 },
  grandNum: { fontSize: 36, fontWeight: 900, color: SEA_DEEP, lineHeight: 1, letterSpacing: '-1px' },
  grandCur: { fontSize: 17, fontWeight: 800, marginInlineStart: 3 },
  dockBtns: { display: 'flex', gap: 8 },
  resetBtn: { flex: 1, padding: 12, borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, color: INK, fontSize: 14, fontWeight: 700, cursor: 'pointer' },
  overlay: { position: 'fixed', inset: 0, background: 'rgba(44,38,32,.55)', display: 'flex', alignItems: 'flex-end', justifyContent: 'center', zIndex: 50 },
  receipt: { background: SAND, width: '100%', maxWidth: 420, maxHeight: '88vh', borderRadius: '20px 20px 0 0', display: 'flex', flexDirection: 'column', overflow: 'hidden', boxShadow: '0 -10px 40px rgba(0,0,0,.2)' },
  receiptHead: { background: SEA, color: '#fff', padding: '18px 20px 14px', textAlign: 'center', flexShrink: 0 },
  receiptBrand: { fontSize: 22, fontWeight: 900, display: 'block' },
  receiptScroll: { flex: 1, overflowY: 'auto', padding: '14px 18px 6px' },
  receiptSection: { marginBottom: 4 },
  receiptNote: { fontSize: 11, fontWeight: 700, color: MUTE, margin: '10px 0 4px' },
  receiptRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', padding: '9px 0', borderBottom: '1px solid ' + LINE, gap: 10 },
  receiptItemName: { fontSize: 15, fontWeight: 700, color: INK, display: 'flex', flexDirection: 'column' },
  receiptItemSub: { fontSize: 11, fontWeight: 600, color: MUTE, marginTop: 2 },
  receiptItemPrice: { fontSize: 15, fontWeight: 800, color: SEA_DEEP, flexShrink: 0 },
  receiptRowSub: { display: 'flex', justifyContent: 'space-between', padding: '5px 0', borderBottom: '1px dotted ' + LINE },
  receiptItemNameSub: { fontSize: 13, fontWeight: 600, color: '#6b6356' },
  receiptItemPriceSub: { fontSize: 13, fontWeight: 700, color: '#b4ab9b' },
  receiptQtyTag: { fontSize: 12, color: MUTE, fontWeight: 700 },
  receiptEmpty: { textAlign: 'center', color: MUTE, fontSize: 14, padding: '30px 0' },
  receiptTotal: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '14px 18px', background: '#fff', borderTop: '1.5px solid ' + LINE, flexShrink: 0 },
  receiptTotalLbl: { fontSize: 14, fontWeight: 700, color: MUTE },
  receiptTotalNum: { fontSize: 34, fontWeight: 900, color: SEA_DEEP },
  receiptTotalCur: { fontSize: 17, fontWeight: 800, marginInlineStart: 3 },
  qrPanel: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8, padding: '14px 18px 4px', background: '#fff', flexShrink: 0 },
  qrImg: { width: 170, height: 170, borderRadius: 16, border: '1.5px solid ' + LINE, padding: 6, background: '#fff' },
  qrHint: { fontSize: 12, fontWeight: 600, color: MUTE },
  receiptBtns: { display: 'flex', gap: 8, margin: '12px 18px calc(14px + env(safe-area-inset-bottom))', flexShrink: 0 },
  receiptClose: { flex: 1, padding: 14, borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, color: INK, fontSize: 15, fontWeight: 700, cursor: 'pointer' },
  qrBtn: { flex: 1.3, padding: 14, borderRadius: 12, border: 'none', background: SUN, color: '#fff', fontSize: 15, fontWeight: 700, cursor: 'pointer' },

  homeHead: { background: SEA, color: '#fff', padding: '12px 16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, flexShrink: 0 },
  homeBrand: { fontSize: 22, fontWeight: 900 },
  homeDate: { fontSize: 12, fontWeight: 700, opacity: 0.95, background: 'rgba(255,255,255,.16)', padding: '5px 11px', borderRadius: 20, whiteSpace: 'nowrap' },
  totalsCard: { display: 'block', width: '100%', textAlign: 'start', background: CARD, border: '1.5px solid ' + LINE, borderRadius: 16, padding: 14, marginBottom: 16, cursor: 'pointer' },
  totalsTitle: { fontSize: 15, fontWeight: 800, color: INK },
  totalsGrid: { display: 'flex', gap: 8 },
  totalCell: { flex: 1, minWidth: 84, background: SAND, borderRadius: 12, padding: '10px 6px', textAlign: 'center' },
  totalCellNum: { fontSize: 20, fontWeight: 900, lineHeight: 1.1, display: 'block', whiteSpace: 'nowrap' },
  totalCellCur: { fontSize: 12, fontWeight: 800 },
  totalCellLbl: { fontSize: 11, fontWeight: 700, color: MUTE, marginTop: 3, display: 'block' },
  sectionLabel: { fontSize: 13, fontWeight: 800, color: MUTE, margin: '2px 2px 10px' },
  // Responsive columns (auto-fill) so the floor scales from 2-up on a phone to more on a
  // tablet instead of two ever-wider cards; align-items:stretch (grid default) + a min-height
  // tall enough for the optional partial-paid row keeps every card the same height, so the
  // grid stays tidy however many tables are open (no ragged rows).
  tablesGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 10 },
  tableCard: { textAlign: 'start', background: CARD, border: '1.5px solid ' + LINE, borderRadius: 16, padding: 13, cursor: 'pointer', display: 'flex', flexDirection: 'column', gap: 9, minHeight: 156, boxShadow: '0 1px 3px rgba(44,38,32,.05)' },
  tableCardHead: { display: 'flex', alignItems: 'center', gap: 9, minWidth: 0 },
  tableMetaRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 6, flexWrap: 'wrap' },
  tableNumBadge: { width: 36, height: 36, borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 17, fontWeight: 900, color: '#fff', lineHeight: 1, flexShrink: 0 },
  tableName: { fontSize: 14, fontWeight: 800, color: INK, flex: 1, minWidth: 0, lineHeight: 1.25, overflowWrap: 'break-word' },
  tableMeta: { fontSize: 12, fontWeight: 600, color: MUTE },
  tablePartPaid: { fontSize: 11, fontWeight: 800, color: SEA_DEEP, background: '#eef6fb', borderRadius: 8, padding: '3px 8px', alignSelf: 'flex-start' },
  tableCardTotal: { marginTop: 'auto', paddingTop: 9, borderTop: '1px solid ' + LINE, display: 'flex', alignItems: 'baseline', justifyContent: 'flex-end', gap: 3 },
  tableCardNum: { fontSize: 25, fontWeight: 900, color: INK, lineHeight: 1 },
  tableCardCur: { fontSize: 14, fontWeight: 800, color: MUTE },
  emptyTables: { textAlign: 'center', color: MUTE, fontSize: 14, fontWeight: 600, padding: '38px 20px', lineHeight: 1.5, background: CARD, borderRadius: 16, border: '1.5px dashed #d9ccb2' },
  homeDock: { background: CARD, borderTop: '1px solid ' + LINE, boxShadow: '0 -6px 24px rgba(44,38,32,.10)', padding: '12px 12px calc(12px + env(safe-area-inset-bottom))', flexShrink: 0, display: 'flex', gap: 8 },
  newTableBtn: { flex: 1, padding: 16, borderRadius: 16, border: 'none', background: SEA, color: '#fff', fontSize: 16, fontWeight: 800, cursor: 'pointer', boxShadow: '0 4px 14px rgba(44,146,191,.25)' },

  tvHead: { background: SEA, color: '#fff', padding: '10px 12px', flexShrink: 0, display: 'flex', flexDirection: 'column', gap: 8 },
  tvTopRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  backBtn: { border: 'none', background: 'rgba(255,255,255,.18)', color: '#fff', fontSize: 13, fontWeight: 700, padding: '8px 12px', borderRadius: 12, cursor: 'pointer', whiteSpace: 'nowrap' },
  tvTitle: { fontSize: 18, fontWeight: 900 },
  cancelTableBtn: { border: 'none', background: 'rgba(255,255,255,.18)', color: '#fff', fontSize: 15, fontWeight: 700, width: 34, height: 34, borderRadius: 12, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 0, flexShrink: 0 },
  nameInput: { width: '100%', padding: '9px 12px', borderRadius: 12, border: 'none', background: 'rgba(255,255,255,.92)', fontSize: 14, fontWeight: 600, color: INK, outline: 'none', textAlign: 'right' },
  payBtn: { flex: 1.4, padding: 12, borderRadius: 12, border: 'none', background: '#3a9e6e', color: '#fff', fontSize: 14, fontWeight: 800, cursor: 'pointer', boxShadow: '0 2px 10px rgba(58,158,110,.25)' },

  payWide: { width: 'auto', margin: '6px 18px 0', padding: 14, borderRadius: 12, border: 'none', background: '#3a9e6e', color: '#fff', fontSize: 15, fontWeight: 800, cursor: 'pointer', boxShadow: '0 2px 10px rgba(58,158,110,.25)' },
  payHead: { background: '#3a9e6e', color: '#fff', padding: '18px 20px 14px', textAlign: 'center', flexShrink: 0 },
  payTotalLbl: { fontSize: 13, opacity: 0.9 },
  payTotalBig: { fontSize: 38, fontWeight: 900, lineHeight: 1.1 },
  payHeadNote: { fontSize: 12, opacity: 0.9, marginTop: 4 },
  payBody: { padding: '16px 18px', display: 'flex', flexDirection: 'column', gap: 12, overflowY: 'auto' },
  payQuick: { display: 'flex', gap: 8 },
  payChip: { flex: 1, padding: '10px 0', borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, color: INK, fontSize: 13, fontWeight: 700, cursor: 'pointer' },
  payChipOn: { background: SEA, color: '#fff', borderColor: 'transparent' },
  tipCalcHead: { fontSize: 13, fontWeight: 800, color: MUTE, textAlign: 'center', marginBottom: -4 },
  // discount attribution picker
  discGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  discChip: { padding: '12px 8px', borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, color: INK, fontSize: 14, fontWeight: 800, cursor: 'pointer' },
  discChipOn: { background: CLAY, color: '#fff', borderColor: 'transparent' },
  discNoteInput: { width: '100%', boxSizing: 'border-box', padding: '11px 12px', borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, fontSize: 15, fontWeight: 600, color: INK, outline: 'none', textAlign: 'right' },
  // open-table balance-due + payment history
  balanceBox: { background: CARD, border: '1.5px solid ' + LINE, borderRadius: 14, padding: '10px 12px', marginBottom: 12 },
  balanceRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 8 },
  balanceLbl: { fontSize: 12, fontWeight: 700, color: MUTE },
  balanceVal: { fontSize: 14, fontWeight: 800, color: INK },
  balanceDue: { fontSize: 18, fontWeight: 900, color: SEA_DEEP },
  payHistRow: { display: 'flex', alignItems: 'center', gap: 8, padding: '6px 0', borderTop: '1px dotted ' + LINE, fontSize: 12, fontWeight: 700 },
  payHistMethod: { color: INK },
  payHistAmt: { marginInlineStart: 'auto', fontWeight: 800, color: INK },
  payHistVoid: { background: 'transparent', border: 'none', color: CLAY, fontSize: 13, fontWeight: 800, cursor: 'pointer', padding: '0 4px' },
  payHistEdit: { background: 'transparent', border: 'none', cursor: 'pointer', color: SEA_DEEP },
  addPayBtn: { width: '100%', padding: 11, marginTop: 6, borderRadius: 12, border: '1.5px dashed ' + SEA, background: 'transparent', color: SEA_DEEP, fontSize: 14, fontWeight: 800, cursor: 'pointer' },

  comboLine: { background: CARD, border: '1.5px solid ' + SUN, borderRadius: 16, padding: '12px', marginBottom: 8, boxShadow: '0 2px 10px rgba(232,131,58,.1)' },
  comboLineTop: { display: 'flex', alignItems: 'center', gap: 8 },
  comboLineName: { flex: 1, fontSize: 15, fontWeight: 800, color: INK },
  comboLinePrice: { fontSize: 14, fontWeight: 800, color: SUN },
  comboLineParts: { display: 'flex', flexWrap: 'wrap', gap: 6, margin: '7px 0 2px' },
  comboPart: { fontSize: 12, fontWeight: 700, color: SEA_DEEP, background: '#eef6fb', borderRadius: 8, padding: '3px 8px' },
  comboLineCtl: { display: 'flex', alignItems: 'center', gap: 14, justifyContent: 'flex-end', marginTop: 8 },
  comboAddRow: { display: 'flex', flexWrap: 'wrap', gap: 8 },
  comboAddBtn: { flex: '1 1 44%', display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 2, background: SAND, border: '1.5px dashed ' + SUN, borderRadius: 12, padding: '12px 14px', cursor: 'pointer', textAlign: 'start' },
  comboAddName: { fontSize: 15, fontWeight: 800, color: INK },
  comboAddPrice: { fontSize: 13, fontWeight: 800, color: SUN },
  comboBody: { padding: '14px 18px', display: 'flex', flexDirection: 'column', gap: 16, overflowY: 'auto' },
  comboIncludes: { fontSize: 13, fontWeight: 700, color: MUTE, background: SAND, borderRadius: 12, padding: '8px 12px' },
  comboSlot: { display: 'flex', flexDirection: 'column', gap: 8 },
  comboSlotLbl: { fontSize: 14, fontWeight: 800, color: INK },
  comboSlotHint: { fontSize: 12, fontWeight: 700, color: MUTE },
  comboOpts: { display: 'flex', flexWrap: 'wrap', gap: 8 },
  comboChip: { padding: '9px 14px', borderRadius: 12, border: '1.5px solid ' + LINE, background: SAND, color: INK, fontSize: 14, fontWeight: 700, cursor: 'pointer' },
  comboStepper: { display: 'flex', alignItems: 'center', gap: 16 },
  comboOther: { border: '1.5px solid ' + LINE, borderRadius: 12, padding: '10px 12px', fontSize: 15, fontWeight: 600, outline: 'none', background: '#fff', width: '100%', boxSizing: 'border-box' },
  receiptComboParts: { fontSize: 12, fontWeight: 600, color: MUTE, padding: '0 4px 6px', marginTop: -2 },

  stFired: { fontSize: 11, fontWeight: 800, padding: '2px 8px', borderRadius: 8, background: '#fef0e0', color: SUN },
  stReady: { fontSize: 11, fontWeight: 800, padding: '2px 8px', borderRadius: 8, background: '#e7f5ee', color: '#2f7d57' },
  stServed: { fontSize: 11, fontWeight: 800, padding: '2px 8px', borderRadius: 8, background: '#eef3ee', color: '#6b7d70' },
  statusChips: { display: 'inline-flex', flexWrap: 'wrap', gap: 4 },
  kitchenStrip: { margin: '0 2px 6px' },
  dayBookedBadge: { margin: '10px 18px 0', padding: '10px 12px', borderRadius: 12, background: '#e7f5ee', color: '#2f7d57', fontSize: 13, fontWeight: 800, textAlign: 'center' },
  dayBookedCorrected: { background: '#fef0e0', color: '#a9791b' },
  kitchenHead: { display: 'flex', gap: 4, flexShrink: 0, alignItems: 'center' },
  fireBtn: { width: '100%', padding: 11, marginBottom: 8, borderRadius: 12, border: 'none', background: SUN, color: '#fff', fontSize: 15, fontWeight: 800, cursor: 'pointer', boxShadow: '0 3px 12px rgba(232,131,58,.25)' },
  fireBtnDone: { background: '#eef3ee', color: '#2f7d57', boxShadow: 'none', cursor: 'default' },
  chefEnterBtn: { flex: 1, padding: 16, borderRadius: 16, border: 'none', background: SUN, color: '#fff', fontSize: 16, fontWeight: 800, cursor: 'pointer', boxShadow: '0 4px 14px rgba(232,131,58,.25)' },
  chefHead: { background: '#1d1a16', color: '#fff', padding: '12px 14px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, flexShrink: 0 },
  chefBack: { background: 'rgba(255,255,255,.14)', border: 'none', color: '#fff', fontSize: 14, fontWeight: 800, padding: '7px 12px', borderRadius: 12, cursor: 'pointer' },
  chefTitle: { fontSize: 20, fontWeight: 900 },
  chefToolbar: { display: 'flex', justifyContent: 'flex-end', padding: '8px 12px 0' },
  chefToggle: { fontSize: 12, fontWeight: 800, color: MUTE, background: CARD, border: '1.5px solid ' + LINE, padding: '7px 12px', borderRadius: 20, cursor: 'pointer' },
  chefToggleOn: { borderColor: SEA, color: SEA_DEEP, background: '#eaf4f9' },
  chefEmpty: { textAlign: 'center', color: MUTE, fontSize: 15, fontWeight: 700, padding: '60px 20px' },
  chefCard: { background: CARD, border: '1.5px solid ' + LINE, borderRadius: 16, padding: 12, marginBottom: 12, boxShadow: '0 2px 10px rgba(44,38,32,.06)' },
  chefCardHead: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 },
  chefTableNum: { width: 42, height: 42, borderRadius: 12, background: '#1d1a16', color: '#fff', fontSize: 18, fontWeight: 900, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  chefCardInfo: { flex: 1, minWidth: 0 },
  chefTableName: { fontSize: 16, fontWeight: 900, color: INK },
  chefTableSub: { fontSize: 12, fontWeight: 700, color: MUTE, marginTop: 2 },
  chefCount: { fontSize: 13, fontWeight: 800, color: SUN, background: '#fef0e0', padding: '4px 10px', borderRadius: 12, flexShrink: 0 },
  chefDish: { display: 'flex', alignItems: 'center', gap: 10, padding: '12px 4px', borderTop: '1px solid ' + LINE },
  chefDishDone: { opacity: 0.5 },
  chefDishMain: { flex: 1, display: 'flex', alignItems: 'center', gap: 10, minWidth: 0 },
  chefDishQty: { fontSize: 20, fontWeight: 900, color: SEA_DEEP, minWidth: 38, textAlign: 'center' },
  chefDishText: { minWidth: 0 },
  chefDishName: { fontSize: 17, fontWeight: 800, color: INK },
  chefDishParts: { fontSize: 13, fontWeight: 600, color: MUTE, marginTop: 3 },
  chefDone: { background: '#3a9e6e', color: '#fff', border: 'none', fontSize: 16, fontWeight: 900, padding: '14px 20px', borderRadius: 12, cursor: 'pointer', flexShrink: 0, boxShadow: '0 2px 10px rgba(58,158,110,.25)' },
  chefUndo: { background: SAND, color: MUTE, border: '1.5px solid ' + LINE, fontSize: 13, fontWeight: 800, padding: '10px 14px', borderRadius: 12, cursor: 'pointer', flexShrink: 0 },

  reportPresets: { display: 'flex', gap: 6, justifyContent: 'center', flexWrap: 'wrap', marginTop: 12 },
  reportPreset: { background: 'rgba(255,255,255,.16)', border: 'none', color: '#fff', fontSize: 12, fontWeight: 800, padding: '6px 13px', borderRadius: 20, cursor: 'pointer' },
  reportPresetOn: { background: '#fff', color: SEA_DEEP },
  reportDates: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, marginTop: 8 },
  reportDash: { color: '#fff', fontWeight: 800 },
  reportRangeNote: { background: '#fff5e9', color: SUN, fontSize: 13, fontWeight: 800, textAlign: 'center', padding: '10px 18px' },
  reportDate: { background: 'rgba(255,255,255,.18)', border: 'none', color: '#fff', fontSize: 13, fontWeight: 800, padding: '7px 11px', borderRadius: 12, colorScheme: 'dark' },
  reportExpand: { display: 'block', margin: '12px auto 0', background: 'transparent', border: '1.5px solid ' + LINE, color: SEA_DEEP, fontSize: 13, fontWeight: 800, padding: '8px 18px', borderRadius: 20, cursor: 'pointer' },
  detailRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '11px 14px', borderBottom: '1px solid ' + LINE },
  detailLbl: { fontSize: 13, fontWeight: 600, color: MUTE },
  detailVal: { fontSize: 14, fontWeight: 800, color: INK },
  reportTiles: { display: 'flex', flexWrap: 'wrap', gap: 8, padding: '14px 18px 4px' },
  reportNet: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', margin: '10px 18px 0', padding: '12px 16px', background: SAND, borderRadius: 16, border: '1.5px solid ' + LINE },
  reportNetLbl: { fontSize: 15, fontWeight: 800, color: INK },
  reportNetNum: { fontSize: 24, fontWeight: 900 },
  reportHint: { fontSize: 11, fontWeight: 600, color: MUTE, textAlign: 'center', margin: '6px 18px 0' },
  reportItemRow: { display: 'flex', alignItems: 'center', gap: 10, padding: '7px 18px' },
  reportItemName: { flex: 1, fontSize: 14, fontWeight: 700, color: INK },
  reportItemQty: { fontSize: 14, fontWeight: 900, color: SEA_DEEP, minWidth: 40, textAlign: 'end' },
  reportItemVal: { fontSize: 13, fontWeight: 700, color: MUTE, minWidth: 64, textAlign: 'end' },
  reportEmptySec: { fontSize: 13, color: MUTE, padding: '4px 18px 8px' },
  costDel: { background: 'transparent', border: 'none', color: MUTE, fontSize: 16, fontWeight: 800, cursor: 'pointer', padding: '0 4px' },
  costAddRow: { display: 'flex', gap: 8, padding: '6px 18px 2px' },
  costNoteInput: { flex: 1, minWidth: 0, border: '1.5px solid ' + LINE, borderRadius: 12, padding: '10px 12px', fontSize: 14, fontWeight: 600, outline: 'none', background: '#fff' },
  costAmtInput: { width: 80, border: '1.5px solid ' + LINE, borderRadius: 12, padding: '10px 12px', fontSize: 14, fontWeight: 800, outline: 'none', background: '#fff', textAlign: 'center' },
  costAdd: { background: SEA, color: '#fff', border: 'none', borderRadius: 12, padding: '0 16px', fontSize: 14, fontWeight: 800, cursor: 'pointer' },

  // Report accordions
  acc: { margin: '10px 18px 0', background: CARD, borderRadius: 16, border: '1.5px solid ' + LINE, overflow: 'hidden' },
  accHead: { width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, padding: '13px 14px', background: 'transparent', border: 'none', cursor: 'pointer', textAlign: 'start' },
  accTitle: { fontSize: 14, fontWeight: 800, color: SEA_DEEP },
  accRight: { display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 },
  accSummary: { fontSize: 13, fontWeight: 800, color: INK },
  accChevron: { fontSize: 12, fontWeight: 800, color: MUTE },
  accBody: { padding: '0 0 8px', borderTop: '1px solid ' + LINE },
  // Expense — three consistent lines so nothing is cut and the layout never
  // shifts with email length: note+amount, then full who/when, then the actions.
  expRow: { display: 'flex', flexDirection: 'column', gap: 7, padding: '10px 14px', borderBottom: '1px solid #f0ead9' },
  expTop: { display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 10 },
  expNote: { flex: 1, minWidth: 0, fontSize: 14, fontWeight: 700, color: INK, overflowWrap: 'anywhere' },
  expAmt: { fontSize: 14, fontWeight: 800, color: SUN, flexShrink: 0 },
  expWhoLine: { fontSize: 11, fontWeight: 600, color: MUTE, overflowWrap: 'anywhere' },
  expActions: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  expChip: { fontSize: 11, fontWeight: 800, padding: '5px 9px', borderRadius: 9, border: '1.5px solid ' + LINE, background: SAND, color: MUTE, cursor: 'pointer' },
  expChipOn: { background: '#eef6fb', borderColor: 'transparent', color: SEA_DEEP },
  expChipPaid: { background: '#e7f5ee', borderColor: 'transparent', color: '#2f7d57', cursor: 'default' },
  expChipRO: { cursor: 'default', opacity: 0.75 },
  expPaidWrap: { display: 'flex', alignItems: 'center', gap: 4 },
  expPaidTick: { fontSize: 13, fontWeight: 900, color: '#2f7d57' },
  expDate: { border: '1.5px solid ' + LINE, borderRadius: 9, padding: '4px 7px', fontSize: 11, fontWeight: 800, color: '#2f7d57', background: '#fff' },
  expUnpay: { background: 'transparent', border: 'none', color: MUTE, fontSize: 13, fontWeight: 800, cursor: 'pointer', padding: '0 2px' },
  expEdit: { background: 'transparent', border: 'none', color: SEA_DEEP, fontSize: 14, fontWeight: 800, cursor: 'pointer', padding: '0 4px' },
  payField: { display: 'flex', alignItems: 'center', gap: 10, background: SAND, border: '1.5px solid ' + LINE, borderRadius: 12, padding: '10px 14px' },
  payFieldLbl: { fontSize: 15, fontWeight: 800, color: INK, minWidth: 62 },
  payInput: { flex: 1, border: 'none', background: 'transparent', fontSize: 22, fontWeight: 800, color: INK, outline: 'none', textAlign: 'left', width: '100%', minWidth: 0 },
  payCur: { fontSize: 16, fontWeight: 800, color: MUTE },
  payRemain: { textAlign: 'center', fontSize: 14, fontWeight: 800, padding: '9px 0', borderRadius: 12 },
  payRemainOk: { background: '#e7f5ee', color: '#2f7d57' },
  payRemainBad: { background: '#fdeee4', color: SUN },
  payBtns: { display: 'flex', gap: 8, margin: '4px 18px calc(16px + env(safe-area-inset-bottom))' },
  payConfirm: { flex: 1.4, padding: 15, borderRadius: 12, border: 'none', fontSize: 16, fontWeight: 800 },

  closedRow: { display: 'flex', alignItems: 'center', gap: 10, padding: '12px 0', borderBottom: '1px solid ' + LINE },
  closedNum: { width: 38, height: 38, borderRadius: 12, background: SEA, color: '#fff', fontSize: 16, fontWeight: 900, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  closedInfo: { flex: 1, minWidth: 0 },
  closedName: { fontSize: 14, fontWeight: 700, color: INK, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  closedSub: { fontSize: 11, fontWeight: 600, color: MUTE, marginTop: 3, display: 'flex', gap: 6, flexWrap: 'wrap', alignItems: 'center' },
  reopenBtn: { border: '1.5px solid ' + LINE, background: SAND, color: INK, fontSize: 12, fontWeight: 700, padding: '7px 10px', borderRadius: 8, cursor: 'pointer', flexShrink: 0 },
  clearBtn: { flex: 1, padding: 14, borderRadius: 12, border: '1.5px solid #e7c9b0', background: '#fdeee4', color: SUN, fontSize: 14, fontWeight: 700, cursor: 'pointer' },

  homeHeadSide: { display: 'flex', alignItems: 'center', gap: 8 },
  totalsTopRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 12 },
  totalsHint: { fontSize: 11, fontWeight: 700, color: SEA, marginTop: 11, textAlign: 'center' },
} satisfies Record<string, CSSProperties>

export default styles
